apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-dev

resources:
  - ../../base

namePrefix: dev-

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: nginx-demo
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
    target:
      kind: HorizontalPodAutoscaler
      name: nginx-demo-hpa

images:
  - name: nginxdemos/hello
    newTag: latest